### ISSUE TITLE
UI - Build a Session / Add Sitting - how to save?

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#14]
When building a new session & selecting 'Sitting' - after entering a time value, it does not show how to save that time.  Is there a "+" button, similar to add gong or talk?

Tested with TestFlight (small phone size display on iPad)

**Comment by gshotwell** [comment]
That's weird, so the blue save button doesn't pop up when you enter a time?

**Comment by chrismorel** [comment]
Okay I think I know what's going on, I think your phone dimensions are iPhone 4, which is shorter and wider than 5-7, nevertheless we should fix this one because it's a usability bug, maybe I'll make the add button a plus rather than a blur save button and put it to the right of the time display. That'll be more consistent anyway.



I see something briefly (a blue button?) when the time screen is first displayed,   It is shown below the time, but is covered over, quickly, when the keypad slides up over it

**Comment by gshotwell** [comment]
Even though this is probably an iPad issue it should be fixed because it affects usability. I think the best option is to move the add button over to the right of the time entry in order to be consistent with the other screens.

**Comment by gshotwell** [comment]
New Behavior: 

![image](https://cloud.githubusercontent.com/assets/8417172/24613976/43e3a338-1860-11e7-85f3-81f0748d9f96.png)

![image](https://cloud.githubusercontent.com/assets/8417172/24613992/4c38759a-1860-11e7-8ebc-da15e424f41e.png)

**Comment by gshotwell** [comment]
Except with the m and s black :)

**Comment by chrismorel** [comment]
Looks good

**Comment by chrismorel** [comment]
works well - on iPad
