### ISSUE TITLE
Selecting free & subscribed talks (Suggestion)

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#18]
When selecting talks for a session, there seems to be a large number of locked (subscriber talks) & only several free ones available.  (These seems different from the current release where there are less restricted.)

Suggestions:
- Consider adding more free talks.
- Consider adding a way of easily distinguishing between free & subscribed - without needing to check each one.   For example, add 2 tabs for the screen:   "Offered" (free) & "Subscriber"

**Comment by gshotwell** [comment]
I think the way we're going to do this is to just have the free ones at the top. We can change which ones are free through the database. Eventually we might want to add in push notifications or something.

**Comment by chrismorel** [comment]
Yes, this would make it easy to find the free ones (having them at the top),  instead having to check each one.
