### ISSUE TITLE
Confirm delete pop-up - only OK option

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#25]
Delete Session pop-up message has a message (display session play count - good idea :-)
but, only has an OK button.

Consider adding a 'Cancel' button, also, in case the person did not intend to delete the session (especially, after they see the count of the play/practice sessions & want to keep it :-)

**Comment by chrismorel** [comment]
On a related point - it's good to have the message about the number of times played (counting one's practice).  Should the message also mention that this count is being removed from their profile?  (Or would the message be too long?)

**Comment by gshotwell** [comment]
Oh yes, this is a good point :)

**Comment by chrismorel** [comment]
Works fine.  Was able to download the latest version & test.
