### ISSUE TITLE
Save Session - no name allowed

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#26]
Save session - does not require the user to enter a name.  If left blank, the session is saved with no name (blank).  Is this fine or should session name be required?

**Comment by gshotwell** [comment]
Hmmm good find. I'm not really sure which way to go with this one. There's no technical problem with them having an unnamed session, so maybe it makes sense to let them have one if they want one? On the other hand it might be nice to have a reminder.

**Comment by chrismorel** [comment]
Yes, I'm not sure either - since it does save fine & displays on the screen.

**Comment by gshotwell** [comment]
Okay since neither of us have strong feelings about it I'm going to close this one
