### ISSUE TITLE
Find a Center - add magnification (+ & -) buttons to map

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#28]
Suggestion: Add + and - (magnification) buttons to the displayed map, similar to other mapping sites (Google maps).

This would make it clear to the user that they can expand and shrink the map to look for centers, especially if there is no center in their area.  I found that you can do this be pinching & expanding the screen.  It would be good to make this more obvious to the user.

---
As a side note, I wonder what the map would display if there is no center in their area?  Would they see the closest center, even if in another city/area?  Is there a way to test this (fake the GPS location)?

It works fine for us in Halifax, showing the Halifax Center - which initially showed it has Shambhala International, but now correctly shows the local Halifax Center.

**Comment by gshotwell** [comment]
Yeah, the way to do this would be to calculate the distance to the nearest center and adjust magnification to the right dimensions. I think that's a good idea, but would be a bit of work. So I'm going to put this under 2.1

**Comment by chrismorel** [comment]
Would + / - button (magnification feature) be much to add?  (though, probably for a later release)

**Comment by gshotwell** [comment]
I'm not sure, I guess another (easier) option would be to just set the default magnification to be bigger.

**Comment by chrismorel** [comment]
The map looks good on the screen - finds & pinpoints the Halifax center.  Not sure if needs magnification, by default.

**Comment by gshotwell** [comment]
Oh I meant just zooming out on the map so there's a higher probability that they'll see a center. Like this: 
![image](https://cloud.githubusercontent.com/assets/8417172/24713386/e497baac-19fb-11e7-8848-4c19a657d8b8.png)

**Comment by chrismorel** [comment]
Yes, that seems good.
