### ISSUE TITLE
Edit session - does not warn if not saved

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#29]
When editing an existing session & changes are made, the user can return to the main screen - without saving - & no message is given.

Should warn the user & give the option to save?  Or is the current behavior fine?

**Comment by gshotwell** [comment]
I think it's probably fine as is. IMO it would be a bit annoying to get an extra notification, and it's not that hard to re-edit a session that you forgot to save.

**Comment by gshotwell** [comment]
We can see if people complain about it and reevaluate later

**Comment by chrismorel** [comment]
Sounds good.
