### ISSUE TITLE
Play session - doesn't count multiple plays, before closing

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#30]
Play a session - 1x & close, the profile count for the session is correct.

Play a session - more than 1 time, before closing, & then go to user profile.  The session count only increased by 1, instead of adding the total times played.

**Comment by gshotwell** [comment]
Hmmmm, good catch! it's iterating the play count when the component unmounts

**Comment by chrismorel** [comment]
I thought that I also saw a case where there was a count, when it should have been 0, but am not sure ... or if it is repeatable (yet :-)  Maybe, when saving an existing one (save as ...) or some other scenario.  I'll try again.  Hmm ...
