### ISSUE TITLE
Find a Center - Halifax area - 'Special Events' location (in ocean :-)

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#35]
Select 'Find a Center' - when you are located in  the HRM (Halifax) area.  

The map displays fine, but shows one location, "Special Events - 1084 Tower Road", in the ocean off outside of Halifax Harbour  (must be an interesting special event :-)

This is likely more of an issue with the mapped locations, than with this feature.  Who would this mapped location issue be reported to?

**Comment by gshotwell** [comment]
This is an SDB issue so I would report it to.... I dunno Benard maybe? All the map data is pulled from the SDB, I do some correction of the data, putting in https and adding in missing websites, but there's no easy way to correct locations and have them synch up with the SBD.

**Comment by chrismorel** [comment]
Ok, thanks
