### ISSUE TITLE
Listen / Build - in previewing, can play multiple talks or gongs at once

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#36]
In the Listen to Contemplation or the Build a Session, the user can preview (listen) to multiple talks (or gongs - in the Builder) at once.  That leads to interesting audio-effects :-)

This is likely a minor issue, since the user can just keep from selecting multiple talks at once :-)

**Comment by gshotwell** [comment]
Yeah, it's kind of a tricky issue to solve as well because each of the gong playing things is it's own component, so I would need to refactor that rather significantly in order to get them to pause the others when any of them are playing.

**Comment by chrismorel** [comment]
Right, it does not seem to be a significant issue.
