### ISSUE TITLE
Listen / Build - when preview or selecting talks show total audio time

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#37]
Suggestion - 
It would be useful to know the length (total time) of a talk when selecting:
- Listen to Contemplation   &
- Build a Session

Currently, when selecting the talk, in either case, you do not know how long it will be. For example, know this when building the session, you need to save the session & then re-open it to see the length of the audio.

Note that this is already shown when playing a saved session.  This is helpful.

**Comment by gshotwell** [comment]
I have no idea how to do this given that the elements of a series can be different lengths, but I guess we could just put the length for the individual talks.

**Comment by chrismorel** [comment]
Ok, I was wondering if it may be a feature / property of the audio file.  So, likely not so easy to do.

[Maybe, in the case of Playing the talk, it is calculated when the audio file is loaded and shown on the Play screen, but this information is not available when selecting the file?  So, we would not have this number for those cases (selecting the file).]

**Comment by gshotwell** [comment]
Yeah, we have the duration of the talks themselves, so that's definitely doable.

**Comment by gshotwell** [comment]
We can also do it at the database level by just changing the name of the talk. Would that work? so it would be "Working with the Body (3 min)"

**Comment by chrismorel** [comment]
Oh, I see. (re-reading your post, above, talk duration is available, but not series.)

Yes, changing the title at the DB level, would be good (or if there is another way that is available) to indicate duration of the talk.

**Comment by chrismorel** [comment]
Seems helpful to know if you are listening to a talk - how long to expect it to go.

**Comment by gshotwell** [comment]
K you should be able to see this reflected in the current version.

**Comment by chrismorel** [comment]
Yes, nice.
