### ISSUE TITLE
Mystery Crashes

### ISSUE THREAD

**Issue by gshotwell** [GShotwell/shambhala_app_issues#42]
App seems to crash when long sitting periods are added, so far this has been observed in the following sessions: 

- 99 minute sitting block

Triple Gong
Placing the mind on the breath
10 minutes
Working with your body
10 minutes
Double Gong

**Comment by gshotwell** [comment]
I think this is related to the way I'm playing silent sounds, I'm going to try a much longer silent sound and see if that works.

**Comment by chrismorel** [comment]
I have also seen crashes with very short sitting times (2 to 5 seconds - just to test / add silence).  Not sure if it is repeatable with longer sit times, but it has happened multiple times.

**Comment by gshotwell** [comment]
I think this is a memory leak with the library I'm using to do the background timing. Which is why we're seeing it happen erratically and on several different session configurations.

**Comment by gshotwell** [comment]
Possible sources of crash: 

- [ ] 1 second silent track which loops
- [ ] code running inside background time
- [ ] background timer itself
