### ISSUE TITLE
Learn to Meditate - crash on reset / rewind

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#43]
The Learn to Meditate session crashes - if you play & reset/rewind (either while it is still playing or after pausing).

**Comment by gshotwell** [comment]
I think this is the same route cause as #42 so am going to close for now

**Comment by chrismorel** [comment]
Another note about this one - in case it helps determine if there is a common issue with #42 or not --
This crash can be reliably repeated and after only playing (Learn to Meditate) for a short time, before resetting.  It sounds like #42 occurs in less predictable ways?

**Comment by gshotwell** [comment]
You were right this was it's own issue. Good find!

**Comment by chrismorel** [comment]
Ok, good.  Yes, this one seemed easier to repeat (vs. the "mystery crash" :-)

**Comment by chrismorel** [comment]
Works fine, now.
