### ISSUE TITLE
Session - delay in loading

### ISSUE THREAD

**Issue by chrismorel** [GShotwell/shambhala_app_issues#44]
When selecting a saved session, there is a noticeable delay in loading the session.  

It can take between 5 to 15 seconds, even for sessions with talks that are only several minutes long.  I don't remember this type of delay before (in earlier versions).

**Comment by gshotwell** [comment]
This is expected, I needed to change the sound playing module because the one which allows streaming doesn't allow the sound to start playing in the background. So I need to preload the file and spin the player.

**Comment by chrismorel** [comment]
I wonder if this type of delay will be a significant issue (bother) for users.

**Comment by gshotwell** [comment]
If you can find a solution I'm all ears

**Comment by gshotwell** [comment]
Long term I would like to have a download handler, but don't want to spend
the time on that now

**Comment by chrismorel** [comment]
Could you explain more about "the one which allows streaming doesn't allow the sound to start playing in the background" ...  
Just saw your new comment - right, maybe to consider for another time.

**Comment by gshotwell** [comment]
I was using react native video, and now am using react native sound. The
requirements are playing local and streaming files, loading in the
background playing in the background, working on both iOS and Android.

**Comment by chrismorel** [comment]
Should this one stay open (& labelled), to show that it may be fixed at a later time?  (what ever you think is best - just an idea for tracking future work)
